name: Deploy Docsify Wiki

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject GitHub Repository Owner
        run: |
          OWNER="${{ github.repository_owner }}"
          if [ "$OWNER" = "adiglows" ]; then
            FOOTER='Made by <a href="https://github.com/'"$OWNER"'" target="_blank">'$OWNER'</a>'
          else
            FOOTER='Forked by <a href="https://github.com/'"$OWNER"'" target="_blank">'$OWNER'</a> from <a href="https://github.com/adiglows" target="_blank">adiglows</a>'
          fi
          # Use printf to safely inject HTML with quotes
          printf '%s' "$FOOTER" > footer.html
          # Replace placeholder in index.html
          sed -i "s|__GITHUB_OWNER__|$(cat footer.html)|g" index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
