name: Update Roles

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch: # manual trigger

jobs:
  update-roles:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run staff fetcher
        run: python staff_fetcher.py

      - name: Run wiki team fetcher
        run: python wiki_team_fetcher.py

      - name: Commit and push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add staff.md wiki_team.md Staff/ Wiki_Team/
          git diff --cached --quiet || git commit -m "Update roles and wiki team"
          git push || true
